version: "3.8"

networks:
  nginx-node:
    driver: bridge

services:
  node-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: node-api
    volumes:
      - ./api:/usr/nodeapi/app
    entrypoint: sh -c "npm install && npm run start"
    networks:
      - nginx-node
    environment:
      PORT: 3000
