version: "3.8"

networks:
  nginx-node:
    driver: bridge

services:
  node-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: node-api
    volumes:
      - ./api:/usr/nodeapi/app
    entrypoint: sh -c "npm install && npm run start"
    networks:
      - nginx-node
    environment:
      PORT: 3000
      MYSQL_PORT: 3306
      MYSQL_HOST: mysql
      MYSQL_USER: fcuser
      MYSQL_PASSWORD: fcpwd
      MYSQL_DATABASE: fcdockerdb

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    networks:
      - nginx-node
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fcdockerdb
      MYSQL_USER: fcuser
      MYSQL_PASSWORD: fcpwd
    volumes:
      - ./.docker/mysql:/var/lib/mysql
